name: "Docker Image Build Deploy"
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Run docker compose
              uses: docker/compose-cli:1
              with:
                  compose-file: docker-compose.yml
                  compose-command: up -d

            - name: Tests
              run: |
                  docker-compose exec app npm test
