name: "Docker Image Build Deploy"
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Run docker compose
              uses: docker/compose-cli-action@v0.1.1
              with:
                  compose-file: "./docker-compose.yml"
                  compose-version: "3.8"
                  context: .
                  project-name: demo_cicd

            - name: Tests
              run: |
                  docker-compose exec app npm test
