name: "Docker Image Build Deploy"

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Run docker compose
              uses: hoverkraft-tech/compose-action@v2.0.2
              with:
                  compose-file: "./docker-compose.yml"

            - name: Tests
              run: |
                  docker compose run app npm test
